# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jared Andrews
email: jared.andrews07@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Big Data | Cancer Research | College Hoops Fan
twitter_username: JMA_Data
github_username: j-andrews7
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jared Andrews"
  avatar : "/assets/images/profile.png"
  bio    : "I'm a PhD student in Molecular Genetics and Genomics at Washington University. My research integrates large-scale 'omics data to help understand and better treat cancer."
  location: "St. Louis, MO"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://j-andrews7.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JMA_Data"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/j-andrews7"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/jared-andrews-431252107"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JMA_Data"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/j-andrews7"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/jared-andrews-431252107"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
